name: Backend workflow

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server.yaml'

  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server.yaml'

defaults:
  run:
    working-directory: server

jobs:

  docker-basic-push:
    name: Build Docker image and push it to DockerHub
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push basic image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: Dockerfile
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/avito-backend:latest"
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/avito-backend:latest
          cache-to: type=inline